version: '3.8'

services:


  bootcampdbdev:
    container_name: bootcampdbdev
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=123456